#!/bin/bash

declare -i VERSION=1
declare PROG_NAME="SimpleTemplate for cPanel & WHM"
declare -i FORCED_INSTALL=0

while getopts fh name
do
    case $name in
        f) FORCED_INSTALL=1;;
        h) echo "Usage $0 [-f]"
            exit;;
    esac
done


echo "Welcome to the $PROG_NAME installer"
echo
echo "Checking for conflicts:" 

declare -i FOUND_CONFLICT=0

for hook in "addondomain/addaddondomain" "addondomain/deladdondomain" "park/park" "park/unpark" "subdomain/addsubdomain" "subdomain/delsubdomain"; do
    if [[ -e /usr/local/cpanel/hooks/$hook ]]; then
        FOUND_CONFLICT=1
        echo "Hook script /usr/local/cpanel/hooks/$hook already exists, conflict!"
    else
        echo "Hook script /usr/local/cpanel/hooks/$hook does not exist, no conflict"
    fi
done

if [[ $FOUND_CONFLICT == 1 && $FORCED_INSTALL == 0 ]]; then
    echo
    echo "Installation terminating."
    echo "The current cPanel & WHM hook system does not support multiple hooks in separate files."
    echo "You must either manually merge the SimpleTemplate hook with the existing hook or"
    echo "remove the existing hook"
    echo
    echo "Optionally you can Force installation. Do this by re-executing $0 with the -f parameter"
    echo "WARNING! Forcing installation will overwrite your existing hooks. Caveat Emptor!"
    exit 255
elif [[ $FORCED_INSTALL == 1 ]]; then
    echo "Forced Install requested!"
    echo "Ignoring hook conflicts."
    echo "Overwriting any pre-existing hooks."
    echo "Press ctrl+c to preserve your existing hooks now!"
    sleep 2
    echo "Goodbye existing hooks"
fi

echo "Installing perl modules (/var/cpanel/perl/SimpleTemplate)"
cp -Rpaf lib/* /var/cpanel/perl

echo
echo "Installing hook scripts"
if [[ ! -d /usr/local/cpanel/hooks/addondomain ]]; then
    mkdir /usr/local/cpanel/hooks/addondomain
fi

for hook in "addondomain/addaddondomain" "addondomain/deladdondomain" "park/park" "park/unpark" "subdomain/addsubdomain" "subdomain/delsubdomain"; do
    cp -paf installation/hooks/$hook /usr/local/cpanel/hooks/$hook
done

echo
echo "Registering hooks"
/usr/local/cpanel/bin/register_hooks

echo
echo "Installing configuration file (/etc/simpletemplate)"

declare ETC_DIR="/etc/simpletemplate"

if [[ ! -e $ETC_DIR && ! -d $ETC_DIR ]]; then
    mkdir $ETC_DIR
    chmod 0750 $ETC_DIR
fi

cp config/simple_template.conf $ETC_DIR

echo

echo "Installing templates (/var/cpanel/templates)"

if [[ ! -d /var/cpanel/templates ]]; then
    echo "FATAL ERROR!!"
    echo "Your system does not have the cPanel templates directory"
    echo "Installation aborting"
    exit 255
fi

if [[ ! -d /var/cpanel/templates/simpletemplate ]]; then
    mkdir /var/cpanel/templates/simpletemplate
    chmod 0750 /var/cpanel/templates/simpletemplate
fi

cp -Rpaf templates/* /var/cpanel/templates/simpletemplate

echo

echo "Installation done"
echo "Post Installation Tasks"
echo "------------------------"
echo "    1. Read the documentation (docs)"
echo "    2. Modify the configuration ($ETC_DIR/simple_template.conf)"