#!/usr/bin/perl

BEGIN{
    unshift( @INC, qw( /var/cpanel/perl /usr/local/cpanel ) );
}

use strict;
use warnings;
use XML::Simple;

local $ENV{'CPANEL_LOGGER_FILE'} = 'simpletemplate.log';

use Cpanel::Logger;
use SimpleTemplate::Add;

my $logger = Cpanel::Logger->new();

my $xml_in;
while( <STDIN> ){
       $xml_in .= $_;
}

if( $xml_in ){
    my $input_params = XMLin( $xml_in );
    if( exists $input_params->{'cpanelevent'}->{'errors'} && keys %{ $input_params->{'cpanelevent'}->{'errors'} } ){
        $logger->logger( {
            'message' => 'XML Data structure not found',
            'level' => 'warn',
            'backtrace' => 1,
            'service' => 'addsubdomain',
            'output' => 1,
            }
        );
    }
    else{
        my $subdomain = $input_params->{'cpanelevent'}->{'params'}->{'param0'}.'.'.$input_params->{'cpanelevent'}->{'params'}->{'param1'};
        my $st = SimpleTemplate::Add->new( $input_params->{'CPDATA'}->{'USER'}, $subdomain, 'sub' );
        if( $st->update_config() ){
            $logger->logger(
                {
                    'message' => 'Added vhost config for '.$subdomain,
                    'level' => 'info',
                    'backtrace' => 0,
                    'service' => 'addsubdomain',
                    'output' => 1,
                }
            );
        }
    }
}
