#!/usr/bin/perl

BEGIN{
    unshift( @INC, qw( /var/cpanel/perl /usr/local/cpanel ) );
}

use strict;
use warnings;
use XML::Simple;

local $ENV{'CPANEL_LOGGER_FILE'} = 'simpletemplate.log';

use Cpanel::Logger;
use SimpleTemplate::Remove;

my $logger = Cpanel::Logger->new();

my $xml_in;
while( <STDIN> ){
       $xml_in .= $_;
}

if( $xml_in ){
    my $input_params = XMLin( $xml_in );

    if( exists $input_params->{'cpanelevent'}->{'errors'} && keys %{ $input_params->{'cpanelevent'}->{'errors'} } ){
        $logger->logger( {
            'message' => 'Errors exist in cpanelevent, not removing vhost configuration',
            'level' => 'warn',
            'backtrace' => 1,
            'service' => 'deladdondomain',
            'output' => 0,
            }
        );
    }
    else{
        my $st = SimpleTemplate::Remove->new( $input_params->{'CPDATA'}->{'USER'}, $input_params->{'cpanelevent'}->{'params'}->{'domain'}, 'addon' );
        if( $st->update_config() ){
            $logger->logger(
                {
                    'message' => 'Removed VirtualHost configuration for '. $input_params->{'cpanelevent'}->{'params'}->{'subdomain'},
                    'level' => 'info',
                    'backtrace' => 0,
                    'service' => 'deladdondomain',
                    'output' => 0
                }
            );
        }
    }
}
else{
    $logger->logger(
        {
            'message' => 'XML Data structure not found',
            'level' => 'warn',
            'backtrace' => 1,
            'service' => 'deladdondomain',
            'output' => 0,
        }
    );
}

